config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions" }

  resources :posts do
    resources :comments, only: [ :create, :destroy ]
    resources :likes, only: [ :create, :destroy ] # Add destroy for unliking
  end

  resources :comments do
    resources :likes, only: [ :create, :destroy ]
  end

  # get "profile", to: "users#profile"
  # Custom profile update route
  resource :profile, only: [:show, :update], controller: 'users', action: :profile
  patch 'profile/update', to: 'users#update_profile', as: :update_profile

  resources :reports, only: [ :index ] do
    collection do
      get "download_report"
    end
  end

  resources :manage_users, only: [ :index, :create, :new , :destroy] do
    member do
      patch "toggle_status", to: "manage_users#toggle_status"
    end
    collection do
      get "upload"         # Display the upload form
      post "upload_users"  # Handle the CSV/XLSX upload
    end
  end

  root "home#index"
  # post 'get_posts', to: 'home#index'

    # idekiq Web UI (Dashboard)
    mount Sidekiq::Web => "/sidekiq"
end













# ----------------------------------------------
# namespace :admin do
#   resources :users do
#     member do
#       post 'activate'
#       post 'deactivate'
#     end

#     collection do
#       get 'filter_by_role'
#     end
#   end
#   resources :posts, only: [:index, :show] # Admin can view posts and comments
#   resources :comments, only: [:destroy]   # Admin can delete comments
# end
# ----------------------------------------------------
# namespace :admin do
#   get 'users', to: 'users#index'
#   get 'users/:id', to: 'users#show'
#   post 'users', to: 'users#create'
#   put 'users/:id', to: 'users#update'
#   delete 'users/:id', to: 'users#destroy'
#   post 'users/:id/activate', to: 'users#activate'
#   post 'users/:id/deactivate', to: 'users#deactivate'

#   get 'users/filter_by_role', to: 'users#filter_by_role'

#   get 'posts', to: 'posts#index'
#   get 'posts/:id', to: 'posts#show'

# end


# member Routes
# Purpose: Used to define routes that act on a specific member (a single record) of the resource.
# URL Structure: Includes the :id of the resource in the URL.
# Example: If you have a posts resource, a member route might be used to like a specific post.

# When the action is specific to a single record (e.g., liking a post, toggling the status of a user).

# ---------------------------------
# collection Routes
# Purpose: Used to define routes that act on the entire collection of the resource (not tied to a specific record).
# URL Structure: Does not include the :id of the resource.
# Example: If you have a posts resource, a collection route might be used to search all posts.
  
 

app/controllers/manage_users_controller.rb
class ManageUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin

  def index
    @users = User.where.not(id: current_user.id).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    generated_password = SecureRandom.hex(8)  # Generate a random password
    @user.password = generated_password

    if @user.save
      assign_roles(@user)

      begin
        UserMailer.byadmin_welcome_email(@user, generated_password).deliver_later  # Sends the email immediately.
      rescue RedisClient::CannotConnectError, Errno::ECONNREFUSED => e
        Rails.logger.error "Sidekiq is not running or Redis is unavailable: #{e.message}"
        UserMailer.byadmin_welcome_email(@user, generated_password).deliver_now    # Enqueues the email to be sent asynchronously.  Adds the email job to a queue.
      end

      redirect_to manage_users_path, notice: "User created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    user = User.find(params[:id])
    if user.destroy
      redirect_to manage_users_path, notice: "User deleted successfully."
    else
      redirect_to manage_users_path, alert: "Failed to delete user."
    end
  end

  def toggle_status
    user = User.find(params[:id])
    user.update(active: !user.active?)

    redirect_to manage_users_path, notice: "User status updated!"
  end

  # Display the file upload form
  def upload
  end

  def upload_users
    file = params[:file]
    if file.present?
      if file.content_type == "text/csv" || file.content_type == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        # Save the uploaded file to a persistent location Saves the file temporarily in the tmp directory.
        saved_file_path = Rails.root.join("tmp", "bulk_upload_#{Time.now.to_i}_#{file.original_filename}")
        File.open(saved_file_path, "wb") { |f| f.write(file.read) }

        # Pass the saved file path to the Sidekiq job
        BulkUserUploadJob.perform_later(saved_file_path.to_s, current_user.email)
        redirect_to manage_users_path, notice: "Bulk user upload has started. You will receive an email with the status."
      else
        redirect_to upload_manage_users_path, alert: "Invalid file format. Please upload a CSV or XLSX file."
      end
    else
      redirect_to upload_manage_users_path, alert: "No file selected."
    end
  end


  #   The uploaded file is now saved to the /tmp folder with a unique filename.
  # ✅ File.open ensures the file data is securely written before passing it to Sidekiq.
  # ✅ The saved file's path is passed to the BulkUserUploadJob

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :password, :password_confirmation)
  end

  def assign_roles(user)
    roles = params[:user][:roles]
    roles.each { |role| user.add_role(role) } if roles.present?
  end

  def authorize_admin
    redirect_to root_path, alert: "Access denied." unless current_user.admin?
  end
  
end

app/helpers/manage_users_helper.rb
module ManageUsersHelper
end

app/views/manage_users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Reports</title>
   <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 m-auto">

   <div id="main-content" class="flex-1 transition-all duration-300">
      <nav class="flex justify-center md:py-2 mx-4">
         <div class="flex w-full md:px-6 justify-between items-center">
             <%= link_to posts_path do %>
            <div class="flex gap-4 p-3 items-center">
               <p class="text-2xl md:text-3xl font-serif font-semibold text-gray-600">User Management</p>
            </div>
            <% end %>
            <div class="flex gap-4 p-2 items-center">
               <%= image_tag current_user.avatar_url, class: "w-10 h-10 rounded-full" %>
               <div class="flex flex-col">
                  <h2 class="text-lg mb-1"><%= current_user.first_name %> <%= current_user.last_name %></h2>
                  <div class="text-sm">Admin</div>
               </div>
            </div>
         </div>
      </nav>

      <div class="w3-container">
         <div class="rounded-xl bg-gray-100 mx-1">
            <div class="container mx-2 md:p-6">
                   <%# link_to "Back to Posts", posts_path, class: "text-blue-500 hover:text-blue-700  inline-block" %>

               <h1 class="text-xl">List of Users</h1>
               <div class="flex flex-col md:flex-row justify-end space-y-2 md:space-y-0 md:space-x-2">
                  <div class="flex justify-end gap-4">
                     
                     <%= link_to upload_manage_users_path, class: "px-4 py-2 text-sm font-medium text-center inline-flex items-center text-blue-600 hover:text-white bg-white rounded-lg hover:bg-blue-500 focus:outline-none focus:ring-blue-300 shadow-lg" do %>
                        <svg class="w-5 h-5 text-black me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 312.602 312.602" fill="currentColor">
                           <path d="M251.52,137.244c-3.966,0-7.889,0.38-11.738,1.134c-1.756-47.268-40.758-85.181-88.448-85.181 c-43.856,0-80.964,32.449-87.474,75.106C28.501,129.167,0,158.201,0,193.764c0,36.106,29.374,65.48,65.48,65.48h54.782 c4.143,0,7.5-3.357,7.5-7.5c0-4.143-3.357-7.5-7.5-7.5H65.48c-27.835,0-50.48-22.645-50.48-50.48c0-27.835,22.646-50.48,50.48-50.48 c1.367,0,2.813,0.067,4.419,0.206l7.6,0.658l0.529-7.61c2.661-38.322,34.861-68.341,73.306-68.341 c40.533,0,73.51,32.977,73.51,73.51c0,1.863-0.089,3.855-0.272,6.088l-0.983,11.968l11.186-4.367 c5.356-2.091,10.99-3.151,16.747-3.151c25.409,0,46.081,20.672,46.081,46.081c0,25.408-20.672,46.08-46.081,46.08 c-0.668,0-20.608-0.04-40.467-0.08c-19.714-0.04-39.347-0.08-39.999-0.08c-4.668,0-7.108-2.248-7.254-6.681v-80.959l8.139,9.667 c2.667,3.17,7.399,3.576,10.567,0.907c3.169-2.667,3.575-7.398,0.907-10.567l-18.037-21.427c-2.272-2.699-5.537-4.247-8.958-4.247 c-3.421,0-6.686,1.548-8.957,4.247l-18.037,21.427c-2.668,3.169-2.262,7.9,0.907,10.567c1.407,1.185,3.121,1.763,4.826,1.763 c2.137,0,4.258-0.908,5.741-2.67l7.901-9.386v80.751c0,8.686,5.927,21.607,22.254,21.607c0.652,0,20.27,0.04,39.968,0.079 c19.874,0.041,39.829,0.081,40.498,0.081c33.681,0,61.081-27.4,61.081-61.08C312.602,164.644,285.201,137.244,251.52,137.244z"></path>
                        </svg>
                        Upload Users
                     <% end %>

                     <%= link_to new_manage_user_path, class: "px-4 py-2 text-sm font-medium text-center inline-flex items-center text-white hover:text-blue-600 bg-blue-500 rounded-lg hover:bg-white focus:outline-none focus:ring-blue-300 shadow-lg" do %>
                        <svg class="w-5 h-5 text-white hover:text-black me-2" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#000000">
                           <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                           <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                           <g id="SVGRepo_iconCarrier">
                              
                              <defs></defs>
                              <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                 <g id="Dribbble-Light-Preview" transform="translate(-180.000000, -2119.000000)" fill="#000000">
                                    <g id="icons" transform="translate(56.000000, 160.000000)">
                                       <path d="M144,1961.99734 L144,1963.99556 L141,1963.99556 L141,1966.9929 L139,1966.9929 L139,1963.99556 L136,1963.99556 L136,1961.99734 L139,1961.99734 L139,1959 L141,1959 L141,1961.99734 L144,1961.99734 Z M132.042,1970.89143 C132.028,1970.89143 132.014,1970.88943 132,1970.88943 C131.986,1970.88943 131.972,1970.89143 131.958,1970.89143 C130.875,1970.86845 130,1969.98524 130,1968.8972 C130,1967.79518 130.897,1966.89898 132,1966.89898 C133.103,1966.89898 134,1967.79518 134,1968.8972 C134,1969.98524 133.125,1970.86845 132.042,1970.89143 L132.042,1970.89143 Z M135.026,1971.4839 C135.625,1970.78552 136,1969.88932 136,1968.8972 C136,1966.69016 134.209,1964.90075 132,1964.90075 C129.791,1964.90075 128,1966.69016 128,1968.8972 C128,1969.88932 128.375,1970.78552 128.974,1971.4839 C126.057,1972.67385 124,1975.63821 124,1978.98224 C124,1979.0222 124.005,1978.98224 124.006,1978.98224 L126,1978.98224 C126,1975.69116 128.669,1972.91263 131.958,1972.88965 C131.972,1972.88965 131.985,1972.89365 132,1972.89365 C132.015,1972.89365 132.028,1972.88965 132.042,1972.88965 C135.331,1972.91263 138,1975.69116 138,1978.98224 L140,1978.98224 C140,1975.63821 137.943,1972.67484 135.026,1971.4839 L135.026,1971.4839 Z" id="profile_plus-[#1351]"></path>
                                    </g>
                                 </g>
                              </g>
                           </g>
                        </svg>
                        Create User
                     <% end %>
                  </div>
               </div>

               <div class="mx-4">
                  <table class="w-full  shadow-md md:p-4 md:mt-4 rounded-lg ">
                     <tbody class="text-black text-sm font-light">
                        <% @users.each do |user| %>
                           <% unless user == current_user %>
                              <tr class="border-b border-gray-200 hover:bg-gray-100 mb-4 rounded-lg bg-white shadow-lg">
                                 <td class="py-3 px-6  flex items-center text-md ">
                                    <%= image_tag user.avatar_url, class: "w-10 h-10 rounded-full mr-3 hover:opacity-80 transition-opacity" %>
                                    <div class="<%= user.active? ? 'text-green-500' : 'text-red-500'  %>">●</div>
                                    &nbsp; <%= user.first_name %> <%= user.last_name %>
                                 </td>

                                 <td class="py-3 px-6 text-center">
                                     <% if user.has_role?(:admin) %>
                                       <div class="text-[8%] md:text-sm ">Admin</div>
                                    <% else %>
                                       <div class="text-[8%] md:text-sm ">User</div>
                                    <% end %>
                                    </td>

                                 <td class="py-3 px-6 text-center"><%= user.phone_number %></td>
                                 <td class="py-3 px-4 text-center"><%= user.email %></td>

                                 <td class="py-3 px-6 text-center">
                                    <% 
                                       common_classes = "text-white focus:outline-none focus:ring-4 font-medium rounded-full text-sm px-4 py-2.5 text-center min-w-[100px]" # Set a fixed width
                                       active_classes = "bg-green-400 hover:bg-green-600 focus:ring-green-300"
                                       inactive_classes = "bg-red-400 hover:bg-red-600 focus:ring-red-300"
                                    %>
                                    <%= button_to user.active? ? "Deactivate" : "Activate",
                                       toggle_status_manage_user_path(user),
                                       method: :patch,
                                       remote: true,
                                       class: "#{common_classes} #{user.active? ? inactive_classes : active_classes}"
                                    %>
                                 </td>


                                 <td class="py-3 px-6 text-center">
                                    <div class="flex gap-3">
                                       <div class="relative inline-block gap-1" x-data="{ open: false }">
                                          <div class="w-12">
                                             <button @click="open = !open" type="button" class="inline-flex justify-center gap-x-1.5 rounded-md bg-white px-3 py-2 hover:cursor-pointer text-sm font-semibold text-gray-900 ring-gray-400 ring-inset hover:bg-gray-50">
                                                <img src="<%= asset_path('dots.svg') %>" alt="">
                                             </button>
                                          </div>
                                          <div x-show="open" @click.outside="open = false" class="absolute right-0 z-10 mt-2 w-16 md:w-16 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black/5 focus:outline-none">
                                             <div class="py-1">
                                                <%# <div class="block py-2 text-sm md:text-lg text-gray-700 font-semibold hover:text-indigo-800">Change Role</div> %>
                                                 <%= link_to "Delete", manage_user_path(user), data: { turbo_method: :delete, confirm: "Are you sure?" }, class: "text-red-600 hover:text-red-800 block py-1 text-sm md:text-lg  font-semibold " %>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </td>
                              </tr>
                           <% end %>
                        <% end %>
                     </tbody>
                  </table>
               </div>
               <%# paginate @users %>
            </div>
         </div>
      </div>
   </div>

   <!-- Flash Message (Centered at Bottom) -->
   <div class="fixed bottom-5 w-[84%]">
      <div id="flash-messages" class="text-center">
         <% if flash[:notice] %>
            <div class="bg-green-200 text-green-800 px-4 py-2 rounded-lg shadow-md">
               <%= flash[:notice] %>
            </div>
         <% elsif flash[:alert] %>
            <div class="bg-red-200 text-red-800 px-4 py-2 rounded-lg shadow-md">
               <%= flash[:alert] %>
            </div>
         <% end %>
      </div>
   </div>

   <!-- Auto Dismiss Flash Message -->
   <script>
      setTimeout(() => {
         const flashMessage = document.getElementById("flash-messages");
         if (flashMessage) {
            flashMessage.style.opacity = "0";
            setTimeout(() => flashMessage.remove(), 500);
         }
      }, 3000); // Hides after 3 seconds
   </script>
</body>
</html>

app/views/manage_users/new.html.erb
<body class="flex">

      <nav class="flex  md:py-2 md:mx-4">
         <div class="flex w-full md:px-6 justify-between items-center">
           <%= link_to manage_users_path do %>
            <div class="flex gap-4 p-3 items-center">
               <p class="text-1xl md:text-3xl font-serif font-semibold text-gray-600">Create User</p>
            </div>
            <% end %>
            <div class="flex gap-4 items-center">
              <%= image_tag current_user.avatar_url, class: "w-6 h-6 md:w-10 md:h-10 rounded-full" %>
               <div class="">
                  <h2 class="md:text-lg mb-1"><%= current_user.first_name %> <%= current_user.last_name %></h2>
               </div>
            </div>
         </div>
      </nav>

      <hr class="w-full">
 
  <div id="main-content" class="flex-1 p-3 md:p-6 transition-all duration-300" >

    <!-- Main Content -->
    <div class="w3-container">
      <div class="rounded-xl bg-gray-100 h-full">
        <!-- Create User Form -->

        <div class="md:p-4  md:m-6 rounded-xl">
          <div class="md:p-6 rounded-lg md:bg-gray-200 md:shadow-lg md:w-[80%] md:m-auto">
            <%= form_with model: @user, url: manage_users_path, method: :post, class: "space-y-6 md:space-y-10 ml-4" do |f| %>

             <%= link_to "Back to Users", manage_users_path, class: "text-blue-500 hover:text-blue-700 md:mb-4 inline-block" %>

              <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <%= f.label :first_name, "First Name", class: "block font-medium text-gray-600" %>
                  <%= f.text_field :first_name, required: true, class: "w-[90%] md:w-full  p-3 border rounded-md focus:ring-2 focus:ring-blue-400" %>
                </div>
                <div>
                  <%= f.label :last_name, "Last Name", class: "block font-medium text-gray-600" %>
                  <%= f.text_field :last_name, class: "w-[90%] md:w-full p-3 border rounded-md focus:ring-2 focus:ring-blue-400" %>
                </div>

                <div>
                  <%= f.label :phone_number, "Mobile No.", class: "block font-medium text-gray-600" %>
                  <%= f.text_field :phone_number, required: true, class: "w-[90%] md:w-full p-3 border rounded-md focus:ring-2 focus:ring-blue-400" %>
                </div>
                <div>
                  <%= f.label :email, "Email", class: "block font-medium text-gray-600" %>
                  <%= f.email_field :email, required: true, class: "w-[90%] md:w-full p-3 border rounded-md focus:ring-2 focus:ring-blue-400" %>
                </div>
              </div>

              <div class="md:mt-4">
                <label class="font-semibold text-gray-700">Assign Role</label>
                <div class="flex gap-4 mt-2">
                  <label class="flex items-center space-x-2">
                    <%= check_box_tag 'user[roles][]', 'admin', @user.has_role?(:admin), class: "h-5 w-5 text-blue-500" %>
                    <span>Admin</span>
                  </label>
                  <label class="flex items-center space-x-2">
                    <%= check_box_tag 'user[roles][]', 'user', true, disabled: true, class: "h-5 w-5 text-gray-400 cursor-not-allowed" %>
                    <span class="text-gray-500">User (Default)</span>
                  </label>
                </div>
              </div>

              <div class="mt-6 mr-2 text-right">
                <%= f.submit "Create User", class: "bg-blue-500 text-white px-6 py-2 rounded-2xl hover:bg-blue-600 transition" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  
  
</body>

app/views/manage_users/upload.html.erb
<%# /home/hp/Desktop/auth2/devise_auth/app/views/manage_users/upload.html.erb %>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Upload Users</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-100 h-screen flex items-center justify-center">
     <%# navbar %>
     <nav class="flex  md:py-2 md:mx-4">
         <div class="flex w-full md:px-6 justify-between items-center">
           <%= link_to manage_users_path do %>
            <div class="flex gap-4 p-3 items-center">
               <p class="text-1xl md:text-3xl font-serif font-semibold text-gray-600">Upload(CSV/XLSX)</p>
            </div>
            <% end %>

            <div class="flex gap-4 items-center">
              <%= image_tag current_user.avatar_url, class: "w-6 h-6 md:w-10 md:h-10 rounded-full" %>
               <div class="">
                  <h2 class="md:text-lg mb-1"><%= current_user.first_name %> <%= current_user.last_name %></h2>
               </div>
            </div>

         </div>
      </nav>

<hr class="w-full">

<div class="container mt-[15%] md:mt-[5%] mx-auto p-6 flex justify-center items-center h-full">
  <div class="bg-white p-6 rounded-lg shadow-md w-full max-w-md  border border-gray-300 rounded-lg shadow-md">
    
    <%= link_to "Back to Users", manage_users_path, class: "text-blue-500 hover:text-blue-700 mb-4 inline-block" %>
    
    <%= form_with url: upload_users_manage_users_path, multipart: true, method: :post, class: "space-y-4" do |f| %>
      <div>
        <label class="block font-semibold">Choose File</label>
        <%= f.file_field :file, required: true, accept: ".csv, .xlsx", class: "border p-2 rounded w-full focus:ring-2 focus:ring-blue-400" %>
      </div>
      <div class="flex justify-center">
        <%= f.submit "Upload", class: "bg-blue-500 text-white px-6 py-2 rounded-lg hover:bg-blue-600 cursor-pointer" %>
      </div>
    <% end %>
  </div>
</div>


</body>
</html>