config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions" }

  resources :posts do
    resources :comments, only: [ :create, :destroy ]
    resources :likes, only: [ :create, :destroy ] # Add destroy for unliking
  end

  resources :comments do
    resources :likes, only: [ :create, :destroy ]
  end

  # get "profile", to: "users#profile"
  # Custom profile update route
  resource :profile, only: [:show, :update], controller: 'users', action: :profile
  patch 'profile/update', to: 'users#update_profile', as: :update_profile

  resources :reports, only: [ :index ] do
    collection do
      get "download_report"
    end
  end

  resources :manage_users, only: [ :index, :create, :new , :destroy] do
    member do
      patch "toggle_status", to: "manage_users#toggle_status"
    end
    collection do
      get "upload"         # Display the upload form
      post "upload_users"  # Handle the CSV/XLSX upload
    end
  end

  root "home#index"
  # post 'get_posts', to: 'home#index'

    # idekiq Web UI (Dashboard)
    mount Sidekiq::Web => "/sidekiq"
end













# ----------------------------------------------
# namespace :admin do
#   resources :users do
#     member do
#       post 'activate'
#       post 'deactivate'
#     end

#     collection do
#       get 'filter_by_role'
#     end
#   end
#   resources :posts, only: [:index, :show] # Admin can view posts and comments
#   resources :comments, only: [:destroy]   # Admin can delete comments
# end
# ----------------------------------------------------
# namespace :admin do
#   get 'users', to: 'users#index'
#   get 'users/:id', to: 'users#show'
#   post 'users', to: 'users#create'
#   put 'users/:id', to: 'users#update'
#   delete 'users/:id', to: 'users#destroy'
#   post 'users/:id/activate', to: 'users#activate'
#   post 'users/:id/deactivate', to: 'users#deactivate'

#   get 'users/filter_by_role', to: 'users#filter_by_role'

#   get 'posts', to: 'posts#index'
#   get 'posts/:id', to: 'posts#show'

# end


# member Routes
# Purpose: Used to define routes that act on a specific member (a single record) of the resource.
# URL Structure: Includes the :id of the resource in the URL.
# Example: If you have a posts resource, a member route might be used to like a specific post.

# When the action is specific to a single record (e.g., liking a post, toggling the status of a user).

# ---------------------------------
# collection Routes
# Purpose: Used to define routes that act on the entire collection of the resource (not tied to a specific record).
# URL Structure: Does not include the :id of the resource.
# Example: If you have a posts resource, a collection route might be used to search all posts.
  
 

app/models/post.rb
# app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user       # A post must belong to a user.
  has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy  #A post can have multiple comments.
  has_many :likes, as: :likeable, dependent: :destroy   # A post can be liked (Polymorphic Association).
  validates :description, presence: true
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :require_admin

    def index
      @users = User.all
      @posts = Post.includes(:user, :comments, :likes).order(created_at: :desc)
      # render 'admin/users/index
    end

    def show
      @post = Post.includes(:comments, :likes).find_by(id: params[:id])
      redirect_to admin_posts_path, alert: "Post not found." if @post.nil?
    end


  def edit
    @post = current_user.posts.find_by(id: params[:id])
    if @post.nil?
      redirect_to posts_path, alert: "You can only edit your own posts."
    end
  # else
  #   @comments = @post.comments.order(created_at: :desc) # Ensures latest comments first
  # end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: "Post created successfully."
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "Post updated successfully."
    else
      render :edit
    end
  end

  
  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post deleted."
  end

  private

  def set_post
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, alert: "Post not found." if @post.nil?
  end

  def post_params
    params.require(:post).permit( :description, :public)
  end

  def authorize_post
    unless @post.public? || @post.user == current_user || current_user.has_role?(:admin)
      # flash[:alert] = "You are not authorized to view this post."
      redirect_to posts_path
    end
  end

    private

    def require_admin
      unless current_user.has_role?(:admin)
        # flash[:alert] = "You are not authorized to access this page."
        redirect_to root_path
      end
    end
  end
end

app/controllers/api/posts_controller.rb
class PostsController < ApplicationController
  def create
    Post.create(description: params[:description])
    render json: { message: "Post is created successfully" }, status: :ok
  end
end

app/controllers/posts_controller.rb
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize_post, only: %i[show edit update destroy]

  def index
    @users = User.all  # Load all users for the sidebar

    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      if @user
        @posts = @user.posts.includes(:comments).order(created_at: :desc)
      else
        redirect_to posts_path, alert: "User not found."
      end
    else
      if current_user.has_role?(:admin)
        @posts = Post.includes(:user, :comments).order(created_at: :desc)
      else
        @posts = Post.where(public: true).or(Post.where(user: current_user)).order(created_at: :desc)
      end
    end
  end

  def show
    @post = Post.includes(:comments).find_by(id: params[:id])
    if @post.nil?
      redirect_to posts_path, alert: "Post not found."
    end
  end

  def edit
    @post = current_user.posts.find_by(id: params[:id])
    if @post.nil?
      redirect_to posts_path, alert: "You can only edit your own posts."
    end
    # else
    #   @comments = @post.comments.order(created_at: :desc) # Ensures latest comments first
    # end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: "Post created successfully."
    else
      # render :new
      redirect_to posts_path, alert: "post content can't be blank"
    end
  end



  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "Post updated successfully."
    else
      render :edit
    end
  end

  def destroy
    if current_user.has_role?(:admin) || @post.user == current_user
      @post.destroy
      redirect_to posts_path, notice: "Post was successfully deleted."
    else
      redirect_to posts_path, alert: "You are not authorized to delete this post."
    end
  end


  private

  def set_post
    # @post = current_user.posts.find_by(id: params[:id])
    @post = Post.find_by(id: params[:id]) # Allow admin to fetch any post
    # puts "Post: #{@post.inspect}" # Debugging statement
    redirect_to posts_path, alert: "Post not found." if @post.nil?
  end

  def post_params
    params.require(:post).permit(:description, :public)
  end

  def authorize_post
    unless @post.public? || @post.user == current_user || current_user.has_role?(:admin)
      # flash[:alert] = "You are not authorized to view this post."
      redirect_to posts_path
    end
  end

  # Finds the post (@post = Post.find(params[:id])).
  # Checks if the current user is authorized:
  # If the user is an admin, they can proceed.
  # If the user is the owner of the post, they can proceed.
  # Otherwise, the user is blocked and redirected to root_path with an error message.
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Post Details</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>

<body class="flex">
  <%= render 'devise/shared/navbar' %>

  <div id="main">
    <!-- NavBar -->
    <div class="w3-container">
      <div class="bg-gray-200 p-2 md:p-4 md:m-6 rounded-xl mt-[30%] md:mt-[10%]">
        <main class="flex flex-col gap-4 bg-gray-200 rounded-2xl md:px-2 py-4 md:px-8 md:py-8">
          <%= form_with model: @post, local: true do |form| %>
            <div class="flex flex-col items-center justify-center py-4 px-2 md:px-8 md:py-8 bg-white rounded-2xl">
              <div class="flex flex-col gap-y-5 w-full px-2">

                <!-- Description -->
                <div>
                  <label for="description" class="block text-base font-medium text-gray-900">Description</label>
                  <div class="mt-2">
                    <%= form.text_area :description, rows: 3, class: "w-full px-4 py-3 bg-[#F5F6F8] rounded-xl focus:outline-none border border-black" %>
                  </div>
                </div>

                <!-- Visibility -->
                <div>
                  <span class="block text-base font-medium text-gray-900">Visibility</span>
                  <div class="flex gap-4 pt-1 mt-2">
                    <label class="flex items-center gap-1 md:gap-2 cursor-pointer">
                      <%= form.radio_button :public, true, checked: @post.public? %>
                      <span class="text-gray-900 text-sm md:text-base">Public</span>
                    </label>

                    <label class="flex items-center gap-1 md:gap-2 cursor-pointer">
                      <%= form.radio_button :public, false, checked: !@post.public? %>
                      <span class="text-gray-900 text-sm md:text-base">Private</span>
                    </label>
                  </div>
                </div>

                <!-- Action Buttons -->
                <div class="flex flex-col md:flex-row justify-between gap-4">
                  <div class="flex justify-around gap-4 md:gap-6">
                    <div class="flex items-center gap-2 hover:cursor-pointer">
                      <img src="<%= asset_path('video.svg') %>" alt="">
                      <p class="text-xs md:text-lg">Live Video</p>
                    </div>
                    <div class="flex items-center gap-2 hover:cursor-pointer">
                      <img src="<%= asset_path('photo.svg') %>" alt="">
                      <p class="text-xs md:text-lg">Photo/Video</p>
                    </div>
                    <div class="flex items-center gap-2 hover:cursor-pointer">
                      <img src="<%= asset_path('feeling.svg') %>" alt="">
                      <p class="text-xs md:text-lg">Feeling</p>
                    </div>
                  </div>

                  <div>
                    <%= form.submit "Update", class: "w-[50%] md:w-full bg-indigo-600 hover:bg-indigo-800 text-white py-3 md:px-8 rounded-lg text-xl font-medium hover:cursor-pointer" %>
                  </div>
                </div>

              </div>
            </div>
          <% end %>
        </main>
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/index.html.erb
<body class="flex">
  <!-- Navbar -->
  <div>
    <%= render 'devise/shared/navbar' %>
  </div>

  <!-- Main Content -->
  <div id="main-content" class="flex-1 transition-all duration-300 pt-16 md:pt-20 <%= current_user&.admin? ? 'md:mr-[19%]' : '' %>">
    <!-- Post Form and Posts List -->
    <div class="w3-container">
      <div class="bg-gray-200 rounded-xl">
        <!-- Post Form -->
        <div class="bg-gray-200 p-4 md:m-4 rounded-xl">
          <%= form_with(model: Post.new, url: posts_path, local: false) do |form| %>
            <div class="bg-white rounded-lg mt-8 md:mx-[2%] my-5 shadow-lg">
              <div class="p-5 md:mx-6">
                <%= form.text_area :description, placeholder: "What's happening...?", 
                     class: "w-full px-4 py-7 bg-[#F5F6F8] rounded-xl focus:outline-none border border-black resize-none" %>
              </div>

              <!-- Public/Private Radio Buttons -->
              <div class="flex flex-col justify-between p-4 border-[#3333334D] mx-6">
                <span class="block text-base font-medium text-gray-900">Visibility</span>
                <div class="flex gap-4 pt-1 mt-2">
                  <div class="flex items-center">
                    <%= form.radio_button :public, "true", checked: true %>
                    <%= form.label :public_true, "Public", class: "text-gray-900 text-sm md:text-base ml-2" %>
                  </div>
                  <div class="flex items-center">
                    <%= form.radio_button :public, "false" %>
                    <%= form.label :public_false, "Private", class: "text-gray-900 text-sm md:text-base ml-2" %>
                  </div>
                </div>
              </div>

              <!-- Media Icons and Submit Button -->
              <div class="flex justify-between p-4 border-[#3333334D] mx-6">
                <div class="flex gap-6 text-gray-600">
                  <div class="flex items-center gap-2 hover:cursor-pointer">
                    <img src="<%= asset_path('video.svg') %>" class="w-5" alt="Live Video">
                    <span class="hidden sm:inline">Video</span>
                  </div>
                  <div class="flex items-center gap-2 hover:cursor-pointer">
                    <img src="<%= asset_path('photo.svg') %>" class="w-5" alt="Photo/Video">
                    <span class="hidden sm:inline">Photo/Video</span>
                  </div>
                  <div class="flex items-center gap-2 hover:cursor-pointer">
                    <img src="<%= asset_path('feeling.svg') %>" class="w-5" alt="Feeling">
                    <span class="hidden sm:inline">Feeling</span>
                  </div>
                </div>
                <%= form.submit "Post", class: "px-4 py-1 md:px-10 md:py-3 bg-[#4378DB] text-white font-medium rounded-lg cursor-pointer" %>
              </div>
            </div>
          <% end %>

          <!-- Posts List -->
          <div class="space-y-4">
            <% if @posts.present? %>
              <% @posts.each do |post| %>
                <div class="md:mx-[2%] bg-white rounded-xl p-4 md:p-6 shadow-md">
                  <div class="flex justify-between items-start mb-3 mx-2">
                    <div class="flex items-center hover:bg-gray-100 p-2 rounded-lg transition-colors">
                      <!-- Avatar -->
                      <%= image_tag post.user.avatar_url, class: "w-10 h-10 rounded-full mr-3 hover:opacity-80 transition-opacity" %>

                      <!-- Name and Timestamp -->
                      <div>
                        <h1 class="text-xl font-semibold text-gray-800 hover:text-blue-600 transition-colors">
                          <%= post.user.first_name %> <%= post.user.last_name %>
                        </h1>
                        <p class="text-sm text-gray-500">
                          <%= time_ago_in_words(post.created_at) %> ago, <%= post.public ? "Public" : "Private" %>
                        </p>
                      </div>
                    </div>

                    <!-- Options Menu -->
                    <div class="flex gap-3">
                      <div class="relative inline-block gap-1" x-data="{ open: false }">
                        <div class="w-12">
                          <button @click="open = !open" type="button" class="inline-flex justify-center gap-x-1.5 rounded-md bg-white px-3 py-2 hover:cursor-pointer text-sm font-semibold text-gray-900 ring-gray-400 ring-inset hover:bg-gray-50" id="menu-button" aria-expanded="true" aria-haspopup="true">
                            <img src="<%= asset_path('dots.svg') %>" alt="">
                          </button>
                        </div>
                        <div x-show="open" @click.outside="open = false" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 z-10 w-32 md:w-32 origin-top-right rounded-md bg-white ring-1 shadow-lg ring-black/5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                          <div role="none">
                            <%= link_to "Show", "posts/#{post.id}", class: "block px-4 py-2 text-sm md:text-lg text-gray-700 font-semibold hover:text-indigo-800" %>
                            <% if current_user.has_role?(:admin) || post.user == current_user %>
                              <%= link_to "Edit", "posts/#{post.id}/edit", class: "block px-4 py-2 text-sm md:text-lg text-gray-700 font-semibold hover:text-indigo-800" %>
                            <% end %>
                            <% if current_user.has_role?(:admin) || post.user == current_user %>
                              <%= link_to "Delete", post_path(post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "block px-4 py-2 text-sm md:text-lg text-gray-700 font-semibold hover:text-indigo-800" %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>

                  <!-- Post Description -->
                  <p class="text-gray-800 mb-4 mx-2 text-sm md:text-xl"><%= post.description %></p>

                  <!-- Likes and Comments Count -->
                  <div class="flex text-sm text-gray-600">
                    <div class="w-1/6 p-2"><%= post.likes.count %> Likes</div>
                    <div class="w-1/4 p-2 flex item-end"><%= post.comments.count %> Comments</div>
                  </div>

                  <!-- Like and Comment Buttons -->
                  <div class="flex gap-[20%] py-3 border-y border-gray-200 mx-2">
                    <%= button_to post_likes_path(post), method: :post, remote: true, class: "like-button", id: "like-button-#{post.id}" do %>
                      <div class="flex flex-row items-center">
                        <% if post.likes.find_by(user: current_user) %>
                          <div class="mr-1">❤️</div>
                        <% else %>
                          <img src="<%= asset_path('dil.svg') %>" alt="Like" class="mr-1 w-5 h-5">
                        <% end %>
                        <span class="text-gray-600 hover:text-blue-600">Like</span>
                      </div>
                    <% end %>
                    <span class="text-gray-600 hover:text-blue-600">💬 Comment</span>
                  </div>

                  <!-- Comment Form -->
                  <%= form_with(model: [post, Comment.new], url: post_comments_path(post), local: false, class: "mt-3") do |form| %>
                    <div class="flex space-x-2 p-2 bg-gray-100 rounded-lg">
                      <%= form.text_field :content, placeholder: "Write a comment...", class: "w-[70%] flex-1 p-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
                      <button class="bg-blue-100 hover:bg-blue-300 p-3 rounded-lg text-lg font-medium text-white hover:cursor-pointer transition">
                        <img src="<%= asset_path('send.svg') %>" class="w-6" alt="arrow">
                      </button>
                    </div>
                  <% end %>

                  <!-- Comments Section -->
                  <div class="mt-4 md:mx-6 space-y-4" x-data="{ expanded: false }">
                    <h1 class="w-full font-medium text-gray-500 text-lg md:text-xl">Comments</h1>
                    <hr class="w-full border-gray-200">

                    <% if post.comments.any? %>
                      <div class="space-y-3">
                        <% post.comments.each_with_index do |comment, index| %>
                          <div x-show="expanded || <%= index < 1 %>" class="flex items-start space-x-3 bg-gray-50 p-2 md:p-4 rounded-lg shadow-sm">
                            <!-- Avatar -->
                            <%= image_tag comment.user.avatar_url, class: "w-10 h-10 rounded-full hover:opacity-80 transition-opacity" %>

                            <div class="flex-1">
                              <div class="flex items-center space-x-2">
                                <strong class="text-gray-800"><%= comment.user.first_name %> <%= comment.user.last_name %></strong>
                                <span class="text-sm text-gray-500"><%= time_ago_in_words(comment.created_at) %> ago</span>
                              </div>
                              <p class="text-gray-600 mt-1"><%= comment.content %></p>
                            </div>

                            <!-- Like Button for Comment -->
                            <div class="flex items-center space-x-2">
                              <%= button_to comment_likes_path(comment), method: :post, class: "like-button", id: "like-button-#{comment.id}" do %>
                                <% if comment.likes.find_by(user: current_user) %>
                                  <div class="mr-1">❤️</div>
                                <% else %>
                                  <img src="<%= asset_path('dil.svg') %>" alt="Like" class="mr-1 w-5 h-5">
                                <% end %>
                                <span class="text-gray-600 hover:text-blue-600"><%= comment.likes.count %> Like</span>
                              <% end %>
                            </div>
                            
                          </div>
                        <% end %>
                      </div>

                      <hr class="w-full border-gray-200">
                      <% if post.comments.count >= 2 %>
                        <div class="flex justify-end">
                          <button @click="expanded = !expanded" class="px-3 md:px-4 py-2 flex items-center text-sm font-semibold text-white bg-blue-500 rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-400 transition">
                            <span x-text="expanded ? 'Show Less' : 'Load More'"></span>
                          </button>
                        </div>
                      <% end %>
                    <% else %>
                      <p class="text-base font-semibold text-gray-500">No comments yet.</p>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <p class="text-gray-600">No posts available.</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Right Sidebar (Admin only) -->
  <div>
    <%= render 'devise/shared/right_sidebar' %>
  </div>
</body>

app/views/posts/show.html.erb
<body class="flex">
  <!-- Navbar -->
  <div class="">
    <%= render 'devise/shared/navbar' %>
  </div>

  <!-- Main Content -->
  <div id="main-content" class="flex-1 transition-all duration-300 pt-20 mx-2">
    <div class="w3-container">
      <div class="bg-gray-200 rounded-xl">
        <!-- Post Details -->
        <div class="bg-gray-200 p-4 md:m-4 rounded-xl">
          <% if @post %>
            <div class="md:mx-[2%] bg-white rounded-xl p-4 md:p-6 shadow-md">
              <div class="flex justify-between items-start mb-3 mx-2">
                <div class="flex items-center hover:bg-gray-100 p-2 rounded-lg transition-colors">
                  <!-- Avatar -->
                  <%= image_tag @post.user.avatar_url, class: "w-10 h-10 rounded-full mr-3 hover:opacity-80 transition-opacity" %>

                  <!-- Name and Timestamp -->
                  <div>
                    <h1 class="text-xl font-semibold text-gray-800 hover:text-blue-600 transition-colors">
                      <%= @post.user.first_name %> <%= @post.user.last_name %>
                    </h1>
                    <p class="text-sm text-gray-500">
                      <%= time_ago_in_words(@post.created_at) %> ago, <%= @post.public ? "Public" : "Private" %>
                    </p>
                  </div>
                </div>

                <!-- Options Menu -->
                <div class="flex gap-3">
                  <div class="relative inline-block gap-1" x-data="{ open: false }">
                    <div class="w-12">
                      <button @click="open = !open" type="button" class="inline-flex justify-center gap-x-1.5 rounded-md bg-white px-3 py-2 hover:cursor-pointer text-sm font-semibold text-gray-900 ring-gray-400 ring-inset hover:bg-gray-50" id="menu-button" aria-expanded="true" aria-haspopup="true">
                        <img src="<%= asset_path('dots.svg') %>" alt="">
                      </button>
                    </div>
                    <div x-show="open" @click.outside="open = false" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 z-10 w-32 md:w-32 origin-top-right rounded-md bg-white ring-1 shadow-lg ring-black/5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                      <div class="" role="none">
                        <% if current_user.has_role?(:admin) || @post.user == current_user %>
                          <%= link_to "Edit", edit_post_path(@post), class: "block px-4 py-2 text-sm md:text-lg text-gray-700 font-semibold hover:text-indigo-800" %>
                        <% end %>
                        <% if current_user.has_role?(:admin) || @post.user == current_user %>
                          <%= link_to "Delete", post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "block px-4 py-2 text-sm md:text-lg text-gray-700 font-semibold hover:text-indigo-800" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Post Description -->
              <p class="text-gray-800 mb-4 mx-2 text-sm md:text-xl"><%= @post.description %></p>

              <!-- Likes and Comments Count -->
              <div class="flex text-sm text-gray-600">
                <div class="w-1/6 p-2"><%= @post.likes.count %> Likes</div>
                <div class="w-1/4 p-2 flex item-end"><%= @post.comments.count %> Comments</div>
              </div>

              <!-- Like and Comment Buttons -->
              <div class="flex gap-[20%] py-3 border-y border-gray-200 mx-2">
                <%= button_to post_likes_path(@post), method: :post, remote: true, class: "like-button", id: "like-button-#{@post.id}" do %>
                  <div class="flex flex-row items-center">
                    <% if @post.likes.find_by(user: current_user) %>
                      <div class="mr-1">❤️</div>
                    <% else %>
                      <img src="<%= asset_path('dil.svg') %>" alt="Like" class="mr-1 w-5 h-5">
                    <% end %>
                    <span class="text-gray-600 hover:text-blue-600">Like</span>
                  </div>
                <% end %>
                <span class="text-gray-600 hover:text-blue-600">💬 Comment</span>
              </div>

              <!-- Comment Form -->
              <%= form_with(model: [@post, Comment.new], url: post_comments_path(@post), local: false, class: "mt-3" ) do |form| %>
                <div class="flex space-x-2 p-2 bg-gray-100 rounded-lg">
                  <%= form.text_field :content, placeholder: "Write a comment...", class: "w-[70%] flex-1 p-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
                  <button class="bg-blue-100 hover:bg-blue-300 p-3 rounded-lg text-lg font-medium text-white hover:cursor-pointer transition">
                    <img src="<%= asset_path('send.svg')%>" class="w-6" alt="arrow">
                  </button>
                </div>
              <% end %>

              <!-- Comments Section -->
              <div class="mt-4 md:mx-6 space-y-4" x-data="{ expanded: false }">
                <h1 class="w-full font-medium text-gray-500 text-lg md:text-xl">Comments</h1>
                <hr class="w-full border-gray-200">
                <% if @post.comments.any? %>
                  <div class="space-y-3">
                    <% @post.comments.each_with_index do |comment, index| %>
                      <div x-show="expanded || <%= index < 1 %>" class="flex justify-between items-start bg-gray-50 p-2 md:p-4 rounded-lg shadow-sm">
                        <div class="flex-1">
                          <div class="flex items-center space-x-2">
                            <strong class="text-gray-800"><%= comment.user.first_name %> <%= comment.user.last_name %></strong>
                            <span class="text-sm text-gray-500"><%= time_ago_in_words(comment.created_at) %> ago</span>
                          </div>
                          <p class="text-gray-600 mt-1"><%= comment.content %></p>
                        </div>

                        <!-- Like Button for Comment -->
                        <div class="flex items-center space-x-2">
                          <%= button_to comment_likes_path(comment), method: :post, class: "like-button", id: "like-button-#{comment.id}" do %>
                            <% if comment.likes.find_by(user: current_user) %>
                              <div class="mr-1">❤️</div>
                            <% else %>
                              <img src="<%= asset_path('dil.svg') %>" alt="Like" class="mr-1 w-5 h-5">
                            <% end %>
                            <span class="text-gray-600 hover:text-blue-600"><%= comment.likes.count %> Like</span>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                  </div>

                  <hr class="w-full border-gray-200">
                  <% if @post.comments.count > 2 %>
                    <div class="flex justify-end">
                      <button @click="expanded = !expanded" class="px-3 md:px-4 py-2 flex items-center text-sm font-semibold text-white bg-blue-600 rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 transition">
                        <span x-text="expanded ? 'Show Less' : 'Load More'"></span>
                      </button>
                    </div>
                  <% end %>
                <% else %>
                  <p class="text-base font-semibold text-gray-500">No comments yet.</p>
                <% end %>
              </div>
            </div>
          <% else %>
            <p class="text-center text-red-500">Post not found.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>


</body>